### PR TITLE
Allow endpoint to be auto-configured by providing desired locale.

### PR DESCRIPTION
**Pull request by dmcquay**

### CODE REVIEW

**Comment by dmcquay** [comment]
Fixes https://github.com/dmcquay/node-apac/issues/62

**Comment by DaanOlbrechts** [comment]
When is this scheduled to be merged & published to npm?

**Comment by dmcquay** [comment]
@DaanOlbrechts - I wasn't in a big hurry to get this out, but if you need it, I can get it out quickly. Let me know.

**Comment by dmcquay** [comment]
@DaanOlbrechts - Nevermind, I just went ahead and published it. v1.4.0. Enjoy!

**Pull request merged**
