### PR TITLE
version: do updates on version

### PR DESCRIPTION
**Pull request by yorkie**
1. update the version to 2013-08-01
2. expose a way to choose the api version in userland

/cc @WesleyYue @dmcquay

### CODE REVIEW

**Comment by yorkie** [comment]
To state what the importance of this commit/patch, in the best practices [article](https://aws.amazon.com/items/1057?externalID=1057):

> ### Use the Latest API Version
> The Amazon Product Advertising API makes frequent releases. Each release either adds functionality or increases the accuracy, speed, and stability of the Amazon Product Advertising API. Most releases do both

And you could check the latest version number of the product advertising API at [this link](https://aws.amazon.com/archives/Product-Advertising-API/8967000559514506).

**Comment by yorkie** [comment]
Ping

**Comment by WesleyYue** [comment]
Hey, thank you for the pull request. I'll update the documentation to reflect the added parameter.

**Comment by WesleyYue** [comment]
Whoops accidentally closed the request before I merged it.

**Comment by yorkie** [comment]
haha, my pleasure :)

**Pull request merged**
